### ISSUE TITLE
Cannot create default method in an interface

### ISSUE THREAD

**Issue by malvee** [jboss-javassist/javassist#137]
I am trying to generate the whole interface file at runtime and I need to add just 1 default method which calls other methods added to the CtClass before. The exception I get:
`Exception in thread "main" javassist.CannotCompileException: [source error] syntax error near "**default Object** get"
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
Caused by: compile error: syntax error near "**default Object get**"
	at javassist.compiler.Parser.parseClassType(Parser.java:984)
	at javassist.compiler.Parser.parseFormalType(Parser.java:192)
	at javassist.compiler.Parser.parseMember1(Parser.java:52)
	at javassist.compiler.Javac.compile(Javac.java:90)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
`
Whats the correct way to add default methods to an interface. The interface was made using makeInterface, and I am adding the default as .addMethod(CtNewMethod.make("default ....", interface))
I am using 3.12.1.GA from maven repo. Thanks.

**Comment by chibash** [comment]
Maybe you don't need "default" in the source...

**Comment by malvee** [comment]
Interface methods are not suppose to have a body right? Without default it throws the error, 
"javassist.CannotCompileException: an interface method must be abstract:"
Why is adding default causing an error, is it not in the grammar of javassist?

**Comment by malvee** [comment]
"The specification is that Javassist's compiler only supports Java 1.4 (yes, old!) syntax."
https://github.com/jboss-javassist/javassist/issues/72

If thats the case, default methods in Interfaces were only introduced in Java 8. Is it possible to upload a version of Javassist that uses Java8 to maven, the latest one in Maven is 3.12.1 and thats very old! Thanks.

**Comment by PastelBelem8** [comment]
I'm currently using version 3.22 and I cannot create default methods,
