### ISSUE TITLE
Adding non-static field to an interface does not cause a CannotCompileException

### ISSUE THREAD

**Issue by hatcherunh** [jboss-javassist/javassist#144]
This is a minor issue, with an easy work-around (don't do it!), but thought you might want to know.

Using this code:

import javassist.*;
class T {
  static public void main(String args[]) throws CannotCompileException,
    NotFoundException, java.io.IOException
  {
    ClassPool pool = ClassPool.getDefault();
    CtClass cc = pool.get("I");
    CtField f = new CtField(CtClass.intType, "i", cc);
    f.setModifiers(Modifier.PUBLIC);
    cc.addField(f);
    cc.writeFile();
  }
}

To edit this interface:

`public interface I {
  default void meth() {
  }
}
`

Does not throw any exceptions, and produces this class file (javap output):

`public interface I {
  public int i;

  public void meth();
    Code:
       0: return
}
`

If you try to use the edited class file with this code:

`class Main {

  public static void main(String args[])
  {

    class C implements I {
      int get() { return i; }
    }

    C c = new C();
    System.out.println(c.get());
 }
}
`
You get:

`Exception in thread "main" java.lang.ClassFormatError: Illegal field modifiers in class I: 0x1
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Main.main(Main.java:10)
`

`java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
`

Using javassist 3.21.0-GA.

**Comment by nickl-** [comment]
> This is a minor issue, with an easy work-around (don't do it!)

LOL thanks for the laughs!!! =)

If, as a developer, you reached the point where you realise you need javassist to get the job done you are implicitly aware of the warning signs "Here be dragons!!" which does not need to be spelled out. The purpose of javassist is to accomplish the impossible so if it allows you to do things you shouldn't it still succeeds. I don't feel it should in anyway attempt to prevent you from doing something, regardless of whether it will work or not.

The exception seems clear enough pointing to what went wrong in order for you to get back in line and stop trying your luck. 

**Suggest close issue
Reason: Works as intended**
