### ISSUE TITLE
Method lookup with multiple declarations

### ISSUE THREAD

**Issue by paulo-raca** [jboss-javassist/javassist#153]
I'm trying to create Wrappers for Android Stubs with Javassist.

```
//Javassist-generated wrapper for a Stub
class StubWrapper extends Stub {
  Stub wrapped;

  public void destroy() {
    this.wrapped.destroy();
  }
} 
```

And the existing classes are:

```
//Base class for all Android services
class Binder {
  private void destroy() {};
  [...]
}

//Public API for an Android Service
interface IService {
  public abstract void destroy();
  [...]
}

//Base class for the service implementation
abstract class Stub extends Binder implements IService {
  [...]
}
```

But Javassist fails with this error:
```
Caused by: compile error: Method destroy is private
	at javassist.compiler.MemberCodeGen.getAccessiblePrivate(MemberCodeGen.java:684)
	at javassist.compiler.MemberCodeGen.atMethodCallCore2(MemberCodeGen.java:623)
	at javassist.compiler.MemberCodeGen.atMethodCallCore(MemberCodeGen.java:586)
	at javassist.compiler.MemberCodeGen.atCallExpr(MemberCodeGen.java:537)
	at javassist.compiler.JvstCodeGen.atCallExpr(JvstCodeGen.java:244)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.compileExpr(CodeGen.java:230)
	at javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:415)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:363)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.Javac.compileBody(Javac.java:223)
	at javassist.CtBehavior.setBody(CtBehavior.java:438)
```

As far as I can tell, the lookup found the private declaration on the superclass, but completely ignored the public declaration on the interface, which shouldn't happen.

The example works fine using a standard java compiler.

I'm currently working around that with a cast, which works fine:
```
    ((IService)this.wrapped).destroy();
```

**Comment by nickl-** [comment]
I wish you gave me something to reproduce the error with, if I have to take a guess... and I hate guessing... the problem is somewhere here:

https://github.com/jboss-javassist/javassist/blob/e41e0790c0cb073e9e2e30071afecfcdc4621d42/src/main/javassist/compiler/MemberResolver.java#L122-L166

Perhaps the private method fills the `maybe` requirement which prevents execution of the `clazz.getInterfaces();` section.


Hope this helps... let us know what you find...

Please consider providing a means to reproduce the fault. A small unit test or even a link to a test project could suffice.
