### ISSUE TITLE
Javassist Incorrect Code when wrapping with try/catch

### ISSUE THREAD

**Issue by loren138** [jboss-javassist/javassist#155]
Java Version: 8
Javassist Version: 3.22.0

After running javassist, some of my test cases error out with VerifyErrors.  I'm not a bytecode expert, but it appears the error occures when the compiler omits the assignment in the try block since it isn't used but doesn't insert a pop command after `invokespecial` leaving an extra item on the stack (which is somehow originally ok).  When I wrap with the try/catch in javassist that pop becomes necessary but isn't added and creates an error?

## Javassist Calls:
```
        CtClass cc;
        try {
            cc = pool.get(testClassToInstrument);
        } catch (NotFoundException e) {
            e.printStackTrace();
            log.println("getting cc failed");
            return;
        }

        CtMethod[] methods = cc.getMethods();

        for (CtMethod testMethod : methods) {
            if (testMethod.getName().startsWith("test")) {
                try {
                    testMethod.instrument(
                        new ExprEditor() {
                            public void edit(Handler m)
                                    throws CannotCompileException
                            {
                                m.insertBefore("throw $1;");
                            }
                        }
                    );
                    testMethod.insertBefore("semanticrt.statedump.dumpObjectState.setDumpTestCase(\""+ testClassName + "." + testMethod.getName()+"\");");
                    CtClass etype = null;
                    try {
                        // In test cases we'll just catch Exceptions not throwables
                        etype = pool.get("java.lang.Exception");
                    } catch (NotFoundException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                    // TODO .state or .retval?
                    // TODO need to do this to constructors too
                    // The exceptionCode must in with a return or throw statement (ie throw $e;) or in this case
                    // since I want to swallow it return ($r)null.  The ($r) part casts to nothing if the method
                    // is supposed to be void.
                    // See addCatch() https://jboss-javassist.github.io/javassist/tutorial/tutorial2.html
                    String exceptionCode = "{ semanticrt.statedump.dumpObjectState.dumpExceptionToFile($e, " +
                            "\"" + outputFileRoot + "."+ testMethod.getName() + ".exception\", false); return; }\n";
                    testMethod.addCatch(exceptionCode, etype);
                    //testmethod.insertAfter("System.out.println($_);");
                } catch (CannotCompileException e) {
                    System.out.println(testMethod);
                    e.printStackTrace();
                }
            }
        }
        try {
            //	System.out.println(outputTestDir);
            cc.writeFile(outputTestDir);
        } catch (CannotCompileException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
```

## Test 16 Original Source:
```
    @Test
    public void test016() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test016");
        try {
            org.apache.commons.math.linear.OpenMapRealMatrix openMapRealMatrix2 = new org.apache.commons.math.linear.OpenMapRealMatrix((int) (byte) 1, (int) (byte) 0);
            //org.junit.Assert.fail("Expected anonymous exception");
        } catch (java.lang.IllegalArgumentException e) {
            if (!e.getClass().isAnonymousClass()) {
                //org.junit.Assert.fail("Expected anonymous exception, got " + e.getClass().getCanonicalName());
            }
        }
    }
```

De-compiled Result Source: (This recompiles into the "expected" byte code above.)
```
    @Test
    public void test016() throws Throwable {
        try {
            dumpObjectState.setDumpTestCase("RegressionTest0.test016");
            if(debug) {
                System.out.format("%n%s%n", new Object[]{"RegressionTest0.test016"});
            }

            try {
                new OpenMapRealMatrix(1, 0);
            } catch (IllegalArgumentException var4) {
                throw var4;
            }
        } catch (Exception var5) {
            dumpObjectState.dumpExceptionToFile(var5, "out-RegressionTest0.test016.exception", false);
        }
    }
```

## Error Generated on Run:
```
[stderr] Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 53
[stderr] Exception Details:
[stderr]   Location:
[stderr]     RegressionTest0.test016()V @53: return
[stderr]   Reason:
[stderr]     Type 'org/apache/commons/math/linear/OpenMapRealMatrix' (current frame, locals[1]) is not assignable to 'RegressionTest0' (stack map, locals[1])
[stderr]   Current Frame:
[stderr]     bci: @39
[stderr]     flags: { }
[stderr]     locals: { 'RegressionTest0', 'org/apache/commons/math/linear/OpenMapRealMatrix' }
[stderr]     stack: { }
[stderr]   Stackmap Frame:
[stderr]     bci: @53
[stderr]     flags: { }
[stderr]     locals: { 'RegressionTest0', 'RegressionTest0', 'org/apache/commons/math/linear/OpenMapRealMatrix' }
[stderr]     stack: { }
[stderr]   Bytecode:
[stderr]     0x0000000: 1256 b80a b5b2 0002 9900 15b2 0003 1204
[stderr]     0x0000010: 04bd 0005 5903 1256 53b6 0007 57bb 0057
[stderr]     0x0000020: 5904 03b7 0058 4ca7 000e 0000 0000 0000
[stderr]     0x0000030: 0000 a7ff f8b1 4d2c bf00 a7ff ff4e 2d13
[stderr]     0x0000040: 0ce1 03b8 0abb b1                      
[stderr]   Exception Handler Table:
[stderr]     bci [29, 39] => handler: 54
[stderr]     bci [0, 61] => handler: 61
[stderr]   Stackmap Table:
[stderr]     same_frame(@29)
[stderr]     same_frame(@42)
[stderr]     append_frame(@53,Object[#953],Object[#1128])
[stderr]     full_frame(@54,{Object[#953]},{Object[#955]})
[stderr]     same_frame(@57)
[stderr]     full_frame(@61,{Object[#953]},{Object[#2749]})
[stderr] 
[stderr] 	at java.lang.Class.forName0(Native Method)
[stdin] JUnit version 4.12
[stderr] 	at java.lang.Class.forName(Class.java:348)
[stderr] 	at org.junit.internal.Classes.getClass(Classes.java:16)
[stderr] 	at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:100)
[stderr] 	at org.junit.runner.JUnitCommandLineParseResult.parseArgs(JUnitCommandLineParseResult.java:50)
[stderr] 	at org.junit.runner.JUnitCommandLineParseResult.parse(JUnitCommandLineParseResult.java:44)
[stderr] 	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:72)
[stderr] 	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
```

## Initial ByteCode:
```
  public void test016() throws java.lang.Throwable;
    Code:
       0: getstatic     #2                  // Field debug:Z
       3: ifeq          24
       6: getstatic     #3                  // Field java/lang/System.out:Ljava/io/PrintStream;
       9: ldc           #4                  // String %n%s%n
      11: iconst_1
      12: anewarray     #5                  // class java/lang/Object
      15: dup
      16: iconst_0
      17: ldc           #86                 // String RegressionTest0.test016
      19: aastore
      20: invokevirtual #7                  // Method java/io/PrintStream.format:(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;
      23: pop
      24: new           #87                 // class org/apache/commons/math/linear/OpenMapRealMatrix
      27: dup
      28: iconst_1
      29: iconst_0
      30: invokespecial #88                 // Method org/apache/commons/math/linear/OpenMapRealMatrix."<init>":(II)V
      33: astore_1
      34: goto          48
      37: astore_1
      38: aload_1
      39: invokevirtual #16                 // Method java/lang/Object.getClass:()Ljava/lang/Class;
      42: invokevirtual #17                 // Method java/lang/Class.isAnonymousClass:()Z
      45: ifne          48
      48: return
    Exception table:
       from    to  target type
          24    34    37   Class java/lang/IllegalArgumentException
```

## Actual Result:
```
  public void test016() throws java.lang.Throwable;
    Code:
       0: ldc           #86                 // String RegressionTest0.test016
       2: invokestatic  #2744               // Method semanticrt/statedump/dumpObjectState.setDumpTestCase:(Ljava/lang/String;)V
       5: getstatic     #2                  // Field debug:Z
       8: ifeq          29
      11: getstatic     #3                  // Field java/lang/System.out:Ljava/io/PrintStream;
      14: ldc           #4                  // String %n%s%n
      16: iconst_1
      17: anewarray     #5                  // class java/lang/Object
      20: dup
      21: iconst_0
      22: ldc           #86                 // String RegressionTest0.test016
      24: aastore
      25: invokevirtual #7                  // Method java/io/PrintStream.format:(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;
      28: pop
      29: new           #87                 // class org/apache/commons/math/linear/OpenMapRealMatrix
      32: dup
      33: iconst_1
      34: iconst_0
      35: invokespecial #88                 // Method org/apache/commons/math/linear/OpenMapRealMatrix."<init>":(II)V
      38: astore_1
      39: goto          53
      42: nop
      43: nop
      44: nop
      45: nop
      46: nop
      47: nop
      48: nop
      49: nop
      50: goto          42
      53: return
      54: astore_2
      55: aload_2
      56: athrow
      57: nop
      58: goto          57
      61: astore_3
      62: aload_3
      63: ldc_w         #3300               // String out-RegressionTest0.test016.exception
      66: iconst_0
      67: invokestatic  #2750               // Method semanticrt/statedump/dumpObjectState.dumpExceptionToFile:(Ljava/lang/Throwable;Ljava/lang/String;Z)V
      70: return
    Exception table:
       from    to  target type
          29    39    54   Class java/lang/IllegalArgumentException
           0    61    61   Class java/lang/Exception
```

## Expected Byte Code (a result of re-compiling the de-compiled source above):
```
  public void test016() throws java.lang.Throwable;
    Code:
       0: ldc           #103                // String RegressionTest0.test016
       2: invokestatic  #3                  // Method semanticrt/statedump/dumpObjectState.setDumpTestCase:(Ljava/lang/String;)V
       5: getstatic     #4                  // Field debug:Z
       8: ifeq          29
      11: getstatic     #5                  // Field java/lang/System.out:Ljava/io/PrintStream;
      14: ldc           #6                  // String %n%s%n
      16: iconst_1
      17: anewarray     #7                  // class java/lang/Object
      20: dup
      21: iconst_0
      22: ldc           #103                // String RegressionTest0.test016
      24: aastore
      25: invokevirtual #8                  // Method java/io/PrintStream.format:(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;
      28: pop
      29: new           #104                // class org/apache/commons/math/linear/OpenMapRealMatrix
      32: dup
      33: iconst_1
      34: iconst_0
      35: invokespecial #105                // Method org/apache/commons/math/linear/OpenMapRealMatrix."<init>":(II)V
      38: pop
      39: goto          45
      42: astore_1
      43: aload_1
      44: athrow
      45: goto          56
      48: astore_1
      49: aload_1
      50: ldc           #106                // String out-RegressionTest0.test016.exception
      52: iconst_0
      53: invokestatic  #19                 // Method semanticrt/statedump/dumpObjectState.dumpExceptionToFile:(Ljava/lang/Throwable;Ljava/lang/String;Z)V
      56: return
    Exception table:
       from    to  target type
          29    39    42   Class java/lang/IllegalArgumentException
           0    45    48   Class java/lang/Exception
```

**Comment by nickl-** [comment]
I can see what you were aiming for but you have made it impossible to review this issue... I have tried!

When I cannot reproduce what you had, I cannot even start to comment on your results. If I can't even comment on your results how am I suppose to be of any assistance? 

If you can perhaps get a simpler example, without all the external dependencies (org.apache.etc) and less all the distracting comments which seems to have more to do with what you still want to accomplish and nothing to do with this issue (this just makes my life even more difficult having to sift through irrelevant data). Provide just the most simplest and basic routines which produce the problem. Please include the full classes and not just snippets and methods as you have done here. You can also add anything else you can think of which I might need to know, consider, configure, use, or do in order for me to reproduce exactly the results that you got.

You provided a lot of information, a lot more than was required, less is more and if it doesn't help to reproduce the fault then please remove it. 
Unfortunately you also left out a lot of information, enough so that even by making assumptions to try and fill in the gaps I was still unable to make it work.

Only If you can help me reproduce what you had, can I attempt to help you find a resolve.

As I already said, I can see what you were aiming for, I can see the `pop` after `invokespecial` but it is impossible for me to make any comment if I do not know exactly how it came to be `astore_1` after `invokespecial` that is the very least you need to do for me, please.

Some useful links which may help you to help me:
[Bug writing guidelines](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines)
[How to write a good bug report: step-by-step instructions](https://musescore.org/en/developers-handbook/how-write-good-bug-report-step-step-instructions)
[How to Report a Bug](http://testthewebforward.org/docs/bugs.html)

**Suggest close issue
Reason: Cannot reproduce.**

**Comment by chibash** [comment]
I could reproduce this bug and fixed it.

**Comment by nickl-** [comment]
@chibash Awesome!! You're the man!

**Comment by yan-khonski-ca** [comment]
How do I get the fix?

**Comment by chibash** [comment]
git clone git@github.com:jboss-javassist/javassist.git
?

**Comment by nickl-** [comment]
Oh yes of course! That makes sense.
Well spotted @yan-khonski-ca
