### ISSUE TITLE
Getting annotations of signature polymorphic methods raises exception

### ISSUE THREAD

**Issue by pietrobraione** [jboss-javassist/javassist#174]
Suppose I want to get the annotations of a signature polymorphic method, e.g.:

    public class Foo {
        public static void main(String[] params) {
            ClassPool cpool = new ClassPool();
            cpool.appendClassPath("/path/to/jre1.8.0/rt.jar");
            CtClass cls = cpool.get("java.lang.invoke.MethodHandle");
            CtClass obj = cpool.get("java.lang.Object[]");
            CtClass[] param = { obj };
            CtMethod m = cls.getDeclaredMethod("invokeExact", param);
            Object[] annotations = m.getAnnotations();
        }
    }

The effect is the following:

    Exception in thread "main" java.lang.IllegalAccessError: class java.lang.invoke.$Proxy0 cannot access its superinterface java.lang.invoke.MethodHandle$PolymorphicSignature
        at java.lang.reflect.Proxy.defineClass0(Native Method)
        at java.lang.reflect.Proxy.access$300(Proxy.java:228)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:642)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
        at java.lang.reflect.WeakCache.get(WeakCache.java:127)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
        at javassist.bytecode.annotation.AnnotationImpl.make(AnnotationImpl.java:72)
        at javassist.bytecode.annotation.Annotation.toAnnotationType(Annotation.java:295)
        at javassist.CtClassType.toAnnoType(CtClassType.java:707)
        at javassist.CtClassType.toAnnotationType(CtClassType.java:612)
        at javassist.CtBehavior.getAnnotations(CtBehavior.java:239)
        at javassist.CtBehavior.getAnnotations(CtBehavior.java:210)
        at Foo.main(Foo.java:27)

Note that I tried only with Java 8. My version of Javassist is 3.21.0-GA.

**Comment by chibash** [comment]
Since Java 8 silently changes its behavior with respect to security, downgrade your Java 8 to an older version or upgrade your Javassist to 3.22.0-GA.

**Comment by pietrobraione** [comment]
Same error with Javassist 3.22.0-GA.

    Exception in thread "main" java.lang.IllegalAccessError: class java.lang.invoke.$Proxy0 cannot access its superinterface java.lang.invoke.MethodHandle$PolymorphicSignature
        at java.lang.reflect.Proxy.defineClass0(Native Method)
        at java.lang.reflect.Proxy.access$300(Proxy.java:228)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:642)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
        at java.lang.reflect.WeakCache.get(WeakCache.java:127)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
        at javassist.bytecode.annotation.AnnotationImpl.make(AnnotationImpl.java:72)
        at javassist.bytecode.annotation.Annotation.toAnnotationType(Annotation.java:295)
        at javassist.CtClassType.toAnnoType(CtClassType.java:707)
        at javassist.CtClassType.toAnnotationType(CtClassType.java:612)
        at javassist.CtBehavior.getAnnotations(CtBehavior.java:239)
        at javassist.CtBehavior.getAnnotations(CtBehavior.java:210)
        at Foo.main(Foo.java:31)

**Comment by chibash** [comment]
Is your Java 8 the latest?

**Comment by pietrobraione** [comment]
Same error with J2SE 1.8.0-152.

**Comment by chibash** [comment]
Unless you really want to get java.lang.invoke.MethodHandle$PolymorphicSignature, try m.getAvailableAnnotations() instead of m.getAnnotations().

**Comment by pietrobraione** [comment]
Same error with m.getAvailableAnnotations() (it invokes m.getAnnotations() that crashes).

**Comment by chibash** [comment]
I could not reproduce the error.  Note that m.getAvailableAnnotations() invokes m.getAnnotations(true), which is different from m.getAnnotations().

**Comment by pietrobraione** [comment]
Could it be the platform? I am on macOS High Sierra 10.13.1. I will also try on Ubuntu and let you know.

**Comment by chibash** [comment]
Did you try Java 9?
