### ISSUE TITLE
doesn't support java8 interface default method?

### ISSUE THREAD

**Issue by chenwei0930** [jboss-javassist/javassist#177]
I use javassit 3.22.0, when I use javassit to build some class, refer to User class, get some error.

`public interface UserI {
	default String getAge(){
		return "12";
	}`

`public class User implements UserI{
	
}
`

> javassist.CannotCompileException: [source error] getAge() not found in ext.example.beanCopy.orika.testInterfaceDefault.User
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)

**Comment by PastelBelem8** [comment]
@chenwei0930 did you manage to compile the code that generated the default method getAge?

**Comment by PastelBelem8** [comment]
Using version 3.22.0-GA, I have implemented an Interface
`public interface UserI { default String y(String s) { System.out.println(s); return s; }}`
Then, I have a class User to which I add the interface UserI and which has a method **x** that I change through Javassist to invoke the **y** method:
`public class User { void x() { } }`

Then, I proceed as follows: 
1. Access the JavaAssist ClassPool
2. Retrieve CtClass instances for classes User and UserI
3. Add CtClass UserI to CtClass User through the addInterface method.
4. Retrieve CtMethod x from CtClass User by invoking getDeclaredMethod ("x");
5. Set the body of the method retrieved in 4.  to be `"{y(\"This is default with Javassist! \");}" `
6. Write to the instance of CtClass associated to the User
7. Freeze the class by invoking ctClass.toClass.
8. I run the method x: `new User().x();`
9. THe output is: `This is default with Javassist!`
