### ISSUE TITLE
unable to insert FOR EACH block through CtMethod.insertAt(int,String)

### ISSUE THREAD

**Issue by manikchand1995** [jboss-javassist/javassist#185]
When I tried to insert code containing **for-each** block by **CtMethod.insertAt(int,String)**, exception occurs !!

```
Caused by: compile error: ; is missing
	at javassist.compiler.Parser.parseDeclarators(Parser.java:626)
	at javassist.compiler.Parser.parseDeclarationOrExpression(Parser.java:583)
	at javassist.compiler.Parser.parseFor(Parser.java:363)
	at javassist.compiler.Parser.parseStatement(Parser.java:261)
	at javassist.compiler.Javac.compileStmnt(Javac.java:565)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
```

**Comment by chibash** [comment]
Javassist does not support for-each.  Use Iterator since for-each is implemented by Iterator at the bytecode level.
