### ISSUE TITLE
NPE in Exception

### ISSUE THREAD

**Issue by frankbenoit** [jboss-javassist/javassist#209]
Hi

Using 3.23.1
I get this exception:
```
Caused by: java.lang.NullPointerException
	at javassist.CannotCompileException.<init>(CannotCompileException.java:77)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:249)
	at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:128)
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:552)
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:537)
	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:473)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:444)
```

Which means the ctor of the CannotCompileException itself creates NPE because it does not expect the argument be null:
```
    public CannotCompileException(Throwable e) {
        super("by " + e.toString());
        message = null;
        initCause(e);
    }
```

Which hides the real message.

Frank

**Comment by frankbenoit** [comment]
The problem is that the cause is the same as the exception itself, hence Throwable return null from getCause().

**Comment by chibash** [comment]
I've fixed this.  Thank you.
