### ISSUE TITLE
CannotCompileException: cannot find android.content.Context

### ISSUE THREAD

**Issue by iamZ2z** [jboss-javassist/javassist#211]
For example:
ClassPool pool = ClassPool.getDefault();
CtClass ctClass=pool.get(className);
CtConstructor ctConstructor = ctClass.getConstructors()[0];
System.out.println(ctConstructor);	//javassist.CtConstructor@53e25b76[public TeenagerConfirmDialog (Landroid/content/Context;)V]
ctConstructor.insertAfter("{String newstr=\"Assist New Content\";}",true);

source:
public TeenagerConfirmDialog(Context context) {
		super(context);
	}

But a wrong:
javassist.CannotCompileException: cannot find android.content.Context
	at javassist.CtBehavior.insertAfter(CtBehavior.java:906)
	at com.assistest.AssistTest.main(AssistTest.java:109)
Caused by: javassist.NotFoundException: android.content.Context
	at javassist.ClassPool.get(ClassPool.java:422)
	at javassist.bytecode.Descriptor.toCtClass(Descriptor.java:571)
	at javassist.bytecode.Descriptor.getParameterTypes(Descriptor.java:424)
	at javassist.CtBehavior.getParameterTypes(CtBehavior.java:323)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:855)
	... 1 more

Whatever I use ctConstructor.insertAfter() or ctConstructor.setBody() can not build

**Comment by DualVectorFoil** [comment]
Did you fix this problem?
