### ISSUE TITLE
Can't find class [CtNewMethod]

### ISSUE THREAD

**Issue by MilieMV** [jboss-javassist/javassist#219]
Hello, I'm trying to redefine a method in a class to add an if statement but when my code tries to access my boolean getter in the agent class it gives me this error : 

`javassist.CannotCompileException: [source error] no such class: me$milie.pack.Agent
        at javassist.CtNewMethod.make(CtNewMethod.java:84)
        at javassist.CtNewMethod.make(CtNewMethod.java:50)
        at me.milie.pack.TimerTransformer.transform(TimerTransformer.java:37)
        at me.milie.pack.TimerTransformer.transform(TimerTransformer.java:22)
        at sun.instrument.TransformerManager.transform(Unknown Source)
        at sun.instrument.InstrumentationImpl.transform(Unknown Source)
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(Unknown Source)
        at me.milie.pack.Agent.agentmain(Agent.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(Unknown Source)
Caused by: compile error: no such class: me$milie.pack.Agent
        at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:479)
        at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:422)
        at javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:329)
        at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:711)
        at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
        at javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
        at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
        at javassist.compiler.CodeGen.compileBooleanExpr(CodeGen.java:260)
        at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:414)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:385)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
        at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:441)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:385)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
        at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
        at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303)
        at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47)
        at javassist.compiler.Javac.compileMethod(Javac.java:175)
        at javassist.compiler.Javac.compile(Javac.java:102)
        at javassist.CtNewMethod.make(CtNewMethod.java:79)
        ... 14 more`
me.milie.pack.Agent.isState() is my boolean getter which return true.

In the new method, the if statement is set by doing that : `if(me.milie.pack.Agent.isState()) {do something}`

Can someone explain me why javassist can't find my class and if it's an issue ?
If you want more explanation, tell me.
Thanks.

**Comment by chibash** [comment]
It seems that appropriate ClassPath is not given to Javassist.
Can you give it explicitly by ClassPool#appendClassPath().

Also let us know the version of your JVM.

**Comment by MilieMV** [comment]
I forgot to say that I'm adding the agent jar file to the "classpath" in my agentmain method : `inst.appendToBootstrapClassLoaderSearch(new JarFile(Agent.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath().replaceFirst("/", "")));`

I tried to do it directly from Javassist : `ClassPool pool = ClassPool.getDefault();
			pool.appendClassPath(new LoaderClassPath(Agent.class.getClassLoader()));`

None of these solutions are working for me, maybe I did something wrong.
I'm running on Java 8_181 64bits.

**Comment by chibash** [comment]
You can also try `ClassPool#appendClassPath(String)`, which is more direct.
Maybe `appendClassPath(Agent.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath().replaceFirst("/", "")))`?
It's not easy to automatically find the current class path, in particular, if Javassist is running as an agent.
