### ISSUE TITLE
StackOverflowError thrown when set the super class to java.lang.Object and a new method is added with System.out.println() statement

### ISSUE THREAD

**Issue by happylee** [jboss-javassist/javassist#245]
I have set a class's super class to java.lang.Object , and added a new method which has "System.out.println()" statement. The follow exception is thrown: Version javassist 3.24.1-GA, JRE: 1.8_144
```
Exception in thread "main" java.lang.StackOverflowError
	at java.util.Hashtable.get(Hashtable.java:363)
	at javassist.ClassPool.getCached(ClassPool.java:217)
	at javassist.ClassPool.get0(ClassPool.java:499)
	at javassist.ClassPool.get(ClassPool.java:419)
	at javassist.CtClassType.getSuperclass(CtClassType.java:816)
	at javassist.CtClassType.getField2(CtClassType.java:1050)
        at javassist.CtClassType.getField2(CtClassType.java:1052)
        at javassist.CtClassType.getField2(CtClassType.java:1052)
	at javassist.CtClassType.getField2(CtClassType.java:1052)
	at javassist.CtClassType.getField2(CtClassType.java:1052)
....................
```

**Comment by NingZhang-Ericsson** [comment]
Could you give the code snippet for troubleshooting?

**Comment by happylee** [comment]
You need to create a Foo class in the classpath

```
    public static void main(String[] args) throws Exception{

        ClassPool pool = ClassPool.getDefault();

        CtClass clazz = null;
        try {
            clazz = pool.makeClass("Foo");
            clazz.setSuperclass(pool.makeClass("java.lang.Object"));

            StringBuilder mainMethod= new StringBuilder("public static void main(String[] args) throws Throwable{System.out.println();}");
            CtMethod m =CtMethod.make(mainMethod.toString(),clazz);
            clazz.addMethod(m);

        } catch (Exception e) {
            e.printStackTrace();
        }finally {
            if (clazz != null) {
                clazz.detach();
            }
        }
    }
```

**Comment by NingZhang-Ericsson** [comment]
Please change 
```
clazz.setSuperclass(pool.makeClass("java.lang.Object"));
```
to:
```
clazz.setSuperclass(pool.get("java.lang.Object"));
```
