### ISSUE TITLE
javassist-android-master

### ISSUE THREAD

**Issue by blstbbcxz** [jboss-javassist/javassist#31]
hi,i'm using javassist-android-master for my project,but when i use "makeClass(inputstream classfile) " (the .class file is in SDCard), javassist throw a EOFException:
java.io.EOFException
at libcore.io.Streams.readFully(Streams.java:83)
at java.io.DataInputStream.readInt(DataInputStream.java:124)
at javassist.bytecode.ClassFile.read(ClassFile.java:767)
at javassist.bytecode.ClassFile.<init>(ClassFile.java:114)
at javassist.CtClassType.<init>(CtClassType.java:94)
at javassist.ClassPool.makeClass(ClassPool.java:748)
at javassist.ClassPool.makeClass(ClassPool.java:726)
at org.jamruby.javassistsample.MainActivity.onCreate(MainActivity.java:66)
at android.app.Activity.performCreate(Activity.java:5104)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2354)
at android.app.ActivityThread.access$600(ActivityThread.java:150)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5191)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
at dalvik.system.NativeStart.main(Native Method)

**Comment by supritamz** [comment]
Any progress on this? Could you please update how you fixed this issue.

**Comment by blstbbcxz** [comment]
it's been a long day i fix this problem，i'm sorry about that i have forgotten how to fix it even fixed or not
