### ISSUE TITLE
javassist.Loader AccessError

### ISSUE THREAD

**Issue by heixiaoma** [jboss-javassist/javassist#314]
Exception in thread "main" java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by javassist.Loader @45283ce2 cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at javassist.Loader.findClass(Loader.java:419)
	at javassist.Loader.loadClass(Loader.java:350)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.System$2.defineClass(System.java:2196)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:65)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:55)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1020)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006)
	at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:306)
	at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:304)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.base/sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:304)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:294)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:227)
	at java.base/sun.reflect.annotation.AnnotationParser.lambda$parseAnnotationArray$2(AnnotationParser.java:736)
	at java.base/sun.reflect.annotation.AnnotationParser.parseArrayElements(AnnotationParser.java:747)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotationArray(AnnotationParser.java:735)
	at java.base/sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:538)
	at java.base/sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:356)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:287)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.reflect.Executable.declaredAnnotations(Executable.java:614)
	at java.base/java.lang.reflect.Executable.declaredAnnotations(Executable.java:612)
	at java.base/java.lang.reflect.Executable.getDeclaredAnnotations(Executable.java:600)
	at java.base/java.lang.reflect.Method.getDeclaredAnnotations(Method.java:704)
	at java.base/java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:537)
	at top.hserver.core.ioc.ref.MemoryInitClass.init(MemoryInitClass.java:43)
	at top.hserver.HServerApplication.iocInit(HServerApplication.java:38)
	at top.hserver.HServerApplication.run(HServerApplication.java:22)
	at top.test.TestWebApp.main(TestWebApp.java:7)

**Comment by NingZhang-e** [comment]
Which javassist version are you using?
And need example code.

**Comment by nagassaki** [comment]
I had a similar problem as @heixiaoma using AdoptOpenJDK 11.0.9.101, Hibernate Entitymanager 5.4.29 and Javassist 3.27.0-GA. I'm trying to emulate a software adaptation scenario where an `author` attribute of the `Book` class is splitted into the `authorFirstName` and `authorLastName` attributes:

```java
ClassPool pool = ClassPool.getDefault();
CtClass stringClass = pool.get("java.lang.String");
CtClass bookClass = pool.get("Book");

bookClass.defrost();

// remove field: author
CtField authorField = bookClass.getDeclaredField("author");
bookClass.removeField(authorField);

// add field: authorFirstName
CtField firstNameField = new CtField(stringClass, "authorFirstName", bookClass);
firstNameField.setModifiers(Modifier.PRIVATE);
bookClass.addField(firstNameField);

// add field: authorLastName
CtField lastNameField = new CtField(stringClass, "authorLastName", bookClass);
lastNameField.setModifiers(Modifier.PRIVATE);
bookClass.addField(lastNameField);

bookClass.toClass();
```

After modifying the `Book` class, I used the Java Relflection API to create a new book instance, and then persist its data in the database using the Hibernate framework. To avoid the duplicate class definition error, I changed the class loader of current thread to the class loader provided by Javassist:

```java
// change class loader
Loader loader = new Loader(pool);
Thread.currentThread().setContextClassLoader(loader);

// Hibernate's stuff
EntityManagerFactory emf = Persistence.createEntityManagerFactory("Default_PU");
EntityManager em = emf.createEntityManager();
EntityTransaction et = em.getTransaction();

// new book instance
Class <?> bookClass = loader.loadClass("Book");
Object book = bookClass.newInstance();

// persist in database
et.begin();
em.persist(book);
et.commit();
em.close();
```

When Hibernate Entitymanager tries to load Hibernate ORM, an exception is thrown:

```
mar 16, 2021 6:47:03 PM org.hibernate.jpa.boot.spi.ProviderChecker hibernateProviderNamesContain
WARN: HHH015016: Encountered a deprecated javax.persistence.spi.PersistenceProvider [org.hibernate.ejb.HibernatePersistence]; [org.hibernate.jpa.HibernatePersistenceProvider] will be used instead.
mar 16, 2021 6:47:04 PM org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation
INFO: HHH000204: Processing PersistenceUnitInfo [name: Default_PU]
mar 16, 2021 6:47:04 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate ORM core version [WORKING]
Exception in thread "main" java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by javassist.Loader @4bbfb90a cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:878)
	at javassist.Loader.findClass(Loader.java:419)
	at javassist.Loader.loadClass(Loader.java:350)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/jdk.internal.misc.Unsafe.defineClass0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1192)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:55)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jboss.logging.Logger.doGetMessageLogger(Logger.java:2573)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2530)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516)
	at org.hibernate.internal.CoreLogging.messageLogger(CoreLogging.java:28)
	at org.hibernate.internal.CoreLogging.messageLogger(CoreLogging.java:24)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.<clinit>(AbstractServiceRegistryImpl.java:48)
	at org.hibernate.boot.registry.StandardServiceRegistryBuilder.build(StandardServiceRegistryBuilder.java:374)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:231)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:175)
	at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:76)
	at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilder(HibernatePersistenceProvider.java:171)
	at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(HibernatePersistenceProvider.java:119)
	at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(HibernatePersistenceProvider.java:61)
	at org.hibernate.jpa.HibernatePersistenceProvider.generateSchema(HibernatePersistenceProvider.java:156)
	at javax.persistence.Persistence.generateSchema(Persistence.java:114)
	at App.main(App.java:17)
```

A normal execution works like this:

```
mar 16, 2021 7:15:44 PM org.hibernate.jpa.boot.spi.ProviderChecker hibernateProviderNamesContain
WARN: HHH015016: Encountered a deprecated javax.persistence.spi.PersistenceProvider [org.hibernate.ejb.HibernatePersistence]; [org.hibernate.jpa.HibernatePersistenceProvider] will be used instead.
mar 16, 2021 7:15:45 PM org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation
INFO: HHH000204: Processing PersistenceUnitInfo [name: Default_PU]
mar 16, 2021 7:15:45 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate ORM core version 5.4.29.Final
mar 16, 2021 7:15:45 PM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
mar 16, 2021 7:15:46 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
...
```

The example works if two executable files are created, the first to modify the `Book` class (this time using the `writeFile()` method to replace the `Book` .class file) and the second to persist a new instance book, and then executed one after the other (to avoid the duplicate class definition error). But I need a scenario in which all the steps are performed in the same executable file at run time.

**Comment by NingZhang-e** [comment]
Could you try using AccessController, like below:
```
AccessController.doPrivileged((PrivilegedAction) () -> new Loader(Thread.currentThread().getContextClassLoader(), pool));
```

I do not have hibernate environment locally and not familar with hibernate.

**Comment by nagassaki** [comment]
Thank you @NingZhang-e! This loader instantiation fix the illegal access error 😄. Now I have another issue with Hibernate:

```
org.hibernate.property.access.spi.PropertyAccessException: Error accessing field [private int Book.id] by reflection for persistent property [Book#id] : Book{id=0, title=The Hitchhiker's Guide to the Galaxy, authorFirstName=Douglas, authorLastName=Adams}
javax.persistence.PersistenceException: org.hibernate.property.access.spi.PropertyAccessException: Error accessing field [private int Book.id] by reflection for persistent property [Book#id] : Book{id=0, title=The Hitchhiker's Guide to the Galaxy, authorFirstName=Douglas, authorLastName=Adams}
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:726)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:706)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at App.main(App.java:130)
Caused by: org.hibernate.property.access.spi.PropertyAccessException: Error accessing field [private int Book.id] by reflection for persistent property [Book#id] : Book{id=0, title=The Hitchhiker's Guide to the Galaxy, authorFirstName=Douglas, authorLastName=Adams}
	at org.hibernate.property.access.spi.GetterFieldImpl.get(GetterFieldImpl.java:75)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.getIdentifier(AbstractEntityTuplizer.java:230)
	at org.hibernate.persister.entity.AbstractEntityPersister.getIdentifier(AbstractEntityPersister.java:5188)
	at org.hibernate.persister.entity.AbstractEntityPersister.isTransient(AbstractEntityPersister.java:4888)
	at org.hibernate.engine.internal.ForeignKeys.isTransient(ForeignKeys.java:294)
	at org.hibernate.event.internal.EntityState.getEntityState(EntityState.java:59)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:95)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:93)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:720)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Can not set int field Book.id to Book
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
	at java.base/jdk.internal.reflect.UnsafeIntegerFieldAccessorImpl.getInt(UnsafeIntegerFieldAccessorImpl.java:56)
	at java.base/java.lang.reflect.Field.getInt(Field.java:594)
	at org.hibernate.property.access.spi.GetterFieldImpl.get(GetterFieldImpl.java:62)
	... 20 more
```

Probably Hibernate must be using the old loader to reference the class. I'll keep trying ... 😓
