### ISSUE TITLE
   javax.persistence.PersistenceException: Unable to configure EntityManagerFactory   

### ISSUE THREAD

**Issue by pankajpkh24** [jboss-javassist/javassist#318]
Hi ,
I am using hibernate hibernate-core  4.2.21.final version 
    hibernate-entitymanager. 4.2.21.final version 
   hibernate commons annotations 3.2.0.final 
  hibernate-jpa 2.0-api : 1.0.1.final

org.javassis 3.22.0.GA

when i am running my application. i am getting the below error 

 javax.persistence.PersistenceException: Unable to configure EntityManagerFactory

Caused by: javax.persistence.PersistenceException: Unable to configure EntityManagerFactory
        at org.hibernate.ejb.Ejb3Configuration.configure(Ejb3Configuration.java:388)
        at org.hibernate.ejb.HibernatePersistence.createEntityManagerFactory(HibernatePersistence.java:58)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at com.wm.dnaplfrm.sdv.app.persistence.PersistenceManager.<init>(PersistenceManager.java:41)

Caused by: java.lang.RuntimeException: Error while reading file:/u/applic/data/hdfs5/hadoop/yarn/local/usercache/p1/__app__.jar
        at org.hibernate.ejb.packaging.NativeScanner.getClassesInJar(NativeScanner.java:131)
        at org.hibernate.ejb.Ejb3Configuration.addScannedEntries(Ejb3Configuration.java:488)
        at org.hibernate.ejb.Ejb3Configuration.addMetadataFromScan(Ejb3Configuration.java:478)
        at org.hibernate.ejb.Ejb3Configuration.configure(Ejb3Configuration.java:364)
        ... 17 more

Caused by: java.io.IOException: invalid constant type: 19 at 5
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1236)
        at javassist.bytecode.ConstPool.read(ConstPool.java:1167)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:175)
        at javassist.bytecode.ClassFile.read(ClassFile.java:777)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:118)
        at org.hibernate.ejb.packaging.AbstractJarVisitor.checkAnnotationMatching(AbstractJarVisitor.java:246)
        at org.hibernate.ejb.packaging.AbstractJarVisitor.executeJavaElementFilter(AbstractJarVisitor.java:212)
        at org.hibernate.ejb.packaging.AbstractJarVisitor.addElement(AbstractJarVisitor.java:173)
        at org.hibernate.ejb.packaging.FileZippedJarVisitor.doProcessElements(FileZippedJarVisitor.java:124)
        at org.hibernate.ejb.packaging.AbstractJarVisitor.getMatchingEntries(AbstractJarVisitor.java:149)
        at org.hibernate.ejb.packaging.NativeScanner.getClassesInJar(NativeScanner.java:128)
        ... 20 more

any help ?

**Comment by Raymond-Naseef** [comment]
What version of Java are you using?

Not sure but have found some things that may help. [ This answer](https://stackoverflow.com/a/46133927/1003157) to same error shows that codes 19 and 20 are for Java 9.

Also, I checked hibernate-core v4.2.21.Final: that was produces October 2015, before Java 9 was released.

Hibernate is coming out with v6 soon (just in Alpha).  One thought is to update to v5.4.16.Final and check your other dependencies.

Hope this helps.

For more related questions, try web search for: Caused by: java.io.IOException: invalid constant type: 19 at 5

**Comment by pankajpkh24** [comment]
Thanks @Raymond-Naseef  for quick response,
Actually I am using java 8 ,in my organization still they are using that  I checked hibernate-core v4.2.21.Final , so currently I can not changes the version all of sudden as many components are depending on that .

**Comment by Raymond-Naseef** [comment]
Is it possible your runtime is using a different version of javassist?  I checked ConstPool.java in org.javassist v3.22.0-GA and line 1236 is end of a method.  I don't think that matches the error log:

> Caused by: java.io.IOException: invalid constant type: 19 at 5
at javassist.bytecode.ConstPool.readOne(ConstPool.java:1236)

Here is the method at that line:
```
1222    private void read(DataInputStream in) throws IOException {
1223        int n = in.readUnsignedShort();

            items = new LongVector(n);
            numOfItems = 0;
            addItem0(null);          // index 0 is reserved by the JVM.

            while (--n > 0) {       // index 0 is reserved by JVM
                int tag = readOne(in);
                if ((tag == LongInfo.tag) || (tag == DoubleInfo.tag)) {
                    addConstInfoPadding();
                    --n;
                }
1235        }
1236    }

```

More a guess than fact: perhaps javassist in the classpath is for Java 9.  It may be possible the issue is with multiple libraries with conflicting dependencies...

**Comment by pankajpkh24** [comment]
@Raymond-Naseef thanks actually the issues were coming from transitive dependency from joda which was mismatching with hibernate, I excluded it it is working now thanks
