### ISSUE TITLE
CtConstructor.insertBefore error: "CannotCompileException: [source error] ; is missing"

### ISSUE THREAD

**Issue by kriegaex** [jboss-javassist/javassist#323]
I use Javassist 3.27.0-GA in my private project in order to implement some kind of mock framework. I insert code like this into constructors in order to "mock" them, i.e. skip object initialisation:

```java
if (my.package.ConstructorMockRegistry.isObjectInConstructionMock()) { 
  super();
  return;
}
```

This works fine for 99% of all target classes, but I have a reproducible failure for constructor `java.lang.AbstractStringBuilder()`. My log says:

```text
[Constructor Mock Transformer] Adding constructor mock capability to constructor java.lang.AbstractStringBuildernull
[Constructor Mock Transformer] if (my.package.ConstructorMockRegistry.isObjectInConstructionMock()) {
  super();
  return;
};
javassist.CannotCompileException: [source error] ; is missing
	at javassist.CtBehavior.insertBefore(CtBehavior.java:806)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:766)
	at my.package.ConstructorMockTransformer.makeConstructorMockable(ConstructorMockTransformer.java:155)
```

As you can see, I am logging both the constructor signature and the string I generated for compilation. The code looks okay and is exactly the same as for hundreds of other constructors calling a default super constructor.

If you look in the JDK source code, the original method is:

```java
/**
 * This no-arg constructor is necessary for serialization of subclasses.
 */
AbstractStringBuilder() {
    value = EMPTYVALUE;
}
```

What I find weird is the way Javassist prints the signature: `java.lang.AbstractStringBuildernull`. Usually default constructor signatures are printed like `java.lang.AbstractStringBuilder()`. Maybe this is a hint of what is going on internally. Maybe Javassist has a problem with a concrete default constructor with package visibility in an abstract class, but this is just a guess.

Please let me know if you need any additional information.

**Comment by kriegaex** [comment]
Exactly.
