### ISSUE TITLE
javassist not work for jdk version 11.0.7

### ISSUE THREAD

**Issue by kexianjun** [jboss-javassist/javassist#344]
javassist version:3.27.0-GA
the following code works fine with jdk version 8
```java
ClassPool classPool = new ClassPool(true);                                                      
classPool.appendClassPath(new LoaderClassPath(Thread.currentThread().getContextClassLoader())); 
String className = "convertClass";                                                              
                                                                                                
CtClass ctClass = classPool.makeClass(className);                                               
String methodCode = "public void hello(String name){System.out.println($1);}";                  
ctClass.addMethod(CtNewMethod.make(methodCode, ctClass));                                       
Object newInstance = ctClass.toClass().newInstance();                                           
Method hello = newInstance.getClass().getMethod("hello", String.class);                         
hello.invoke(newInstance, "hello");                                                             
```
but when I upgrade jdk version to 11.0.7, It causes the following Exception,how can I fix it?

Exception in thread "main" java.lang.NullPointerException
	at org.apache.ibatis.javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
	at org.apache.ibatis.javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151)
	at org.apache.ibatis.javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134)
	at org.apache.ibatis.javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95)
	at org.apache.ibatis.javassist.ClassPool.toClass(ClassPool.java:1143)
	at org.apache.ibatis.javassist.ClassPool.toClass(ClassPool.java:1106)
	at org.apache.ibatis.javassist.ClassPool.toClass(ClassPool.java:1064)
	at org.apache.ibatis.javassist.CtClass.toClass(CtClass.java:1275)
	at util.bean.BeanCopyUtil.main(BeanCopyUtil.java:415)

**Comment by NingZhang-e** [comment]
This is not official javassist release. Please double check the package name.
```
org.apache.ibatis.javassist.CtClass
```

**Comment by kexianjun** [comment]
> This is not official javassist release. Please double check the package name.
> 
> ```
> org.apache.ibatis.javassist.CtClass
> ```

Checked, and it works.Thank you

**Comment by duantihua** [comment]
The sample code doesn't work on the JDK16,although it can run on JDK11.
