### ISSUE TITLE
NotFoundException in Androd-Gradle-Plugin's Transform API

### ISSUE THREAD

**Issue by Harlber** [jboss-javassist/javassist#345]
- javassist version
```java
implementation 'org.javassist:javassist:3.27.0-GA'
```
 - AGP version
```java
implementation 'com.android.tools.build:gradle:3.4.2'
```

code like this:
```java
     def incrementalClassRoot = new File(path).getParentFile().absolutePath
// path:/Users/hana/StudioProjects/AppMethodTime/app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/zjw/appmethodtime/MyApplication.class
     classPathArrayList.add(pool.appendClassPath(incrementalClassRoot))
     String className = "com.zjw.appmethodtime.MyApplication";
     CtClass c = pool.getCtClass(className)
```
Then I got exception:
```java
javassist.NotFoundException: com.zjw.appmethodtime.MyApplication
	at javassist.ClassPool.get(ClassPool.java:430)
	at javassist.ClassPool.getCtClass(ClassPool.java:495)
	at javassist.ClassPool$getCtClass$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
```

But it works in Unit Test:
```java
    @Test
    public void testClassOperate(){
        ClassPool pool = ClassPool.getDefault();
        String fullClass = "/Users/hana/StudioProjects/AppMethodTime/app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/zjw/appmethodtime/MyApplication.class";

        String parentPath = new File(fullClass).getParentFile().getAbsolutePath();
        String className = "com.zjw.appmethodtime.MyApplication";
        ClassPath classPath = null;
        try {
            classPath = pool.appendClassPath(parentPath);
            CtClass c = pool.getCtClass(className);
            if (c.isFrozen()) {
                c.defrost();
            }
            CtMethod[] methods = c.getDeclaredMethods();
            for (CtMethod method : methods){
                System.out.println(method.getName() + method.getMethodInfo().getCodeAttribute().toString());
            }
        }catch (Throwable e){
            e.printStackTrace();
        }finally {
            if (classPath != null) {
                pool.removeClassPath(classPath);
            }
        }
    }
```

**Comment by Harlber** [comment]
Caused by error context,close it
