### ISSUE TITLE
addCatch will conflict at Modifier.STATIC and throw Exception

### ISSUE THREAD

**Issue by rufherg** [jboss-javassist/javassist#354]
JDK1.8u152
javassist 3.27.0.GA

Hi, I meet a bug that I could not found the reason.
Maybe I overlooked some knowledge about java because the time of learning Java is not long.
Could u help me to analyze the reasons?

this is the test code(just generate a class)

        ClassPool pool = GenerateClass.getClassPool();
        pool.importPackage("java.io");

        CtConstructor ctConstructor = new CtConstructor(new CtClass[]{},ct);
        ctConstructor.setBody("{}");

        CtMethod ctMethod = new CtMethod(CtClass.booleanType, "write",
                new CtClass[]{pool.get("[B"), pool.get("java.lang.String")}, ct);
        ctMethod.setBody("{File file = new File($2);" +
                "FileOutputStream fos = new FileOutputStream(file);" +
                "fos.write($1);fos.flush();fos.close();return true;}");
        ctMethod.setModifiers(Modifier.PRIVATE + Modifier.STATIC);
        ctMethod.addCatch("return false;",pool.get("java.lang.Exception")); // will throw Exception

        ct.addMethod(ctMethod);

The expected class(decompile) result is

        import java.io.File;
        import java.io.FileOutputStream;
        
        public class sqMaLS8793908324700 {
            private static boolean write(byte[] var1, String var2) {
                try {
                    File var3 = new File(var2);
                    FileOutputStream var4 = new FileOutputStream(var3);
                    var4.write(var1);
                    var4.flush();
                    var4.close();
                    return true;
                } catch (Exception var6) {
                    return false;
                }
            }
        
            public sqMaLS8793908324700() {
            }
        }

The exception information is:

        Exception in thread "main" javassist.CannotCompileException: by javassist.bytecode.BadBytecode: write ([BLjava/lang/String;)Z in iIFMVA9620381250500: conflict: *top* and java.lang.String
	        at javassist.CtBehavior.addCatch(CtBehavior.java:1104)
	        at javassist.CtBehavior.addCatch(CtBehavior.java:1048)
	        at serialtool.dynamic.Upload.setUploadFun(Upload.java:58)
	        at serialtool.dynamic.Upload.getCtClass(Upload.java:24)
	        at serialtool.dynamic.Upload.getClass(Upload.java:14)
	        at serialtool.dynamic.Upload.main(Upload.java:67)
        Caused by: javassist.bytecode.BadBytecode: write ([BLjava/lang/String;)Z in iIFMVA9620381250500: conflict: *top* and java.lang.String
	        at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:111)
	        at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:423)
	        at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:405)
	        at javassist.CtBehavior.addCatch(CtBehavior.java:1096)
	        ... 5 more
        Caused by: javassist.bytecode.BadBytecode: conflict: *top* and java.lang.String
	        at javassist.bytecode.stackmap.TypeData$BasicType.setType(TypeData.java:134)
	        at javassist.bytecode.stackmap.Tracer.checkParamTypes(Tracer.java:930)
	        at javassist.bytecode.stackmap.Tracer.doInvokeMethod(Tracer.java:801)
	        at javassist.bytecode.stackmap.Tracer.doOpcode148_201(Tracer.java:595)
	        at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:81)
	        at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:187)
	        at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:164)
	        at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:108)
	        ... 8 more

I try to debug in order to found reason. I guess the reason maybe in the judge for static.
Some source code in the javassist.bytecode.stackmap.TypedBlock:

    void initFirstBlock(int maxStack, int maxLocals, String className, String methodDesc, boolean isStatic, boolean isConstructor) throws BadBytecode {
        if (methodDesc.charAt(0) != '(') {
            throw new BadBytecode("no method descriptor: " + methodDesc);
        } else {
            this.stackTop = 0;
            this.stackTypes = TypeData.make(maxStack);
            TypeData[] locals = TypeData.make(maxLocals);
            if (isConstructor) {
                locals[0] = new UninitThis(className);
            } else if (!isStatic) { // i think is here
                locals[0] = new ClassName(className);
            } 

So I try to make addCatch method before static modification in order to skip the judge for static, juse like this :

        ctMethod.setModifiers(Modifier.PRIVATE + Modifier.STATIC);
        ctMethod.addCatch("return false;",pool.get("java.lang.Exception"));
       
        >>>>>change to

        ctMethod.addCatch("return false;",pool.get("java.lang.Exception"));
        ctMethod.setModifiers(Modifier.PRIVATE + Modifier.STATIC);

it work, the class can be generated normally(also can be used normally). But it will hava some bug, just like can't decompile.(use idea decompile)

        public class sqMaLS8793908324700 {
            private static byte[] content = new byte[]{(byte)66, (byte)68};
            private static String path = "E:\\1.txt";
        
            private static boolean write(byte[] param0, String param1) {
                // $FF: Couldn't be decompiled
            }
        
            public sqMaLS8793908324700() {
            }
        }

So I don't know how to solve the problem exactly (can use and decompile normally), thx ~~

**Comment by chibash** [comment]
Changing a normal method into a static method often crash the bytecode.
Because a normal method implicitly takes "this" as the first parameter but a static methods does not,
just adding the static modifier to the method crashes the bytecode.

So use the following method and give `Modifier.STATIC` as `modifeirs` when creating a CtMethod.
You must create a CtMethod object for a static method.

```
public static CtMethod make(int modifiers, CtClass returnType,
                                String mname, CtClass[] parameters,
                                CtClass[] exceptions,
                                String body, CtClass declaring)
```

**Comment by rufherg** [comment]
Wow! That's totally awesome!
It seems to be my lack of knowledge in Java and javassist. ^_^
I think I need to learn more about java.
Thanks for your help ，it let me learn more.
