### ISSUE TITLE
CtMethod insert code block， throw javassist.CannotCompileException

### ISSUE THREAD

**Issue by ljppttfn** [jboss-javassist/javassist#365]
Javassist CtMethod insert code block:
agent.jar:

                    m.insertBefore("try{\n" +
                            "                    java.util.Map pm = new java.util.HashMap();\n" +
                            "                    for(String p: pm.keySet()){\n" +
                            "                          System.out.println(\"p\");"+
                            "                    }\n" +
                            "                }catch (Exception e){\n" +
                            "                    e.printStackTrace();\n" +
                            "                }");

Another  SpringBoot application configure `-javaagent:agent.jar` .
Then run error:

  javassist.CannotCompileException: [source error] ; is missing
	  at javassist.CtBehavior.insertBefore(CtBehavior.java:806)
	  at javassist.CtBehavior.insertBefore(CtBehavior.java:766)
	  at cn.fudata.qa.HttpAgentClassFileTransformer.transform(HttpAgentClassFileTransformer.java:59)

how to do that?

**Comment by waldi5001** [comment]
`{java.util.List pm = new java.util.ArrayList();for (Object o : pm){ }}` it seems a problem while parsing the for statement.

`Caused by: compile error: ; is missing
	at javassist.compiler.Parser.parseDeclarators(Parser.java:643)
	at javassist.compiler.Parser.parseDeclarationOrExpression(Parser.java:600)
	at javassist.compiler.Parser.parseFor(Parser.java:380)
	at javassist.compiler.Parser.parseStatement(Parser.java:279)
	at javassist.compiler.Parser.parseBlock(Parser.java:307)
	at javassist.compiler.Parser.parseStatement(Parser.java:261)
	at javassist.compiler.Javac.compileBody(Javac.java:219)
	at javassist.CtBehavior.setBody(CtBehavior.java:466)
	... 13 more`

**Comment by chibash** [comment]
Ah... only old-fashioned syntax is supported.
