### ISSUE TITLE
javassist cannot work on jdk 16

### ISSUE THREAD

**Issue by duantihua** [jboss-javassist/javassist#369]
When I test sample code of #344 (javassist not work for jdk version 11.0.7) on jdk 16,it fails and throws a InaccessibleObjectException. 

` Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5c0369c4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:159)
	at javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:213)
	at javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:52)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260) `

So I wonder whether the sample is not right on jdk16 or javassit is not ready for the new jdk.

**Comment by NingZhang-e** [comment]
Please look at below code and its Javadoc.
https://github.com/jboss-javassist/javassist/blob/master/src/main/javassist/CtClass.java#L1297

Please do not use `ctClass.toClass()` anymore, try to `ctClass.toClass(neigborClass)` as replacement.

**Comment by duantihua** [comment]
@NingZhang-e thank you for your solution,it does work.By the way, will the `ctClass.toClass()` method  be deprecated in the future?

**Comment by chibash** [comment]
Do you think it should be @deprecated now?
It works if you're using JDK 8 or so.

**Comment by NingZhang-e** [comment]
I do not think it should be deprecated now unless javassist only support >JDK11 , but it will support JDK 8 for some time.

And one thing to mention, even toClass() could be supported on JDK8, but if the jars in classpath are signed jars, you might need to switch to:
`cc.toClass(Thread.currentThread().getContextClassLoader(), neighborClass.getProtectionDomain());`

**Comment by copbint** [comment]
There is some case, when a target class has no neighbor, can we support input package name, or parse package automatically? Thanks!

**Comment by nswish** [comment]
if there is no neighborclass , and how to sovle this?
