### ISSUE TITLE
NullPointerException on detatch

### ISSUE THREAD

**Issue by laeubi** [jboss-javassist/javassist#370]
I thee the following NPE ocasionally when detaching a class

```
java.lang.NullPointerException
        at java.base/java.util.Hashtable.put(Unknown Source)
        at javassist.ClassPool.cacheCtClass(ClassPool.java:236)
        at javassist.CtClass.detach(CtClass.java:1427)
```
Code used here:
```
CtClass ctClass = pool.makeClass(new ByteArrayInputStream(getClassBytes()));
try {
	//do something with the class...
} finally {
	ctClass.detach();
}
```

As I cache ClassPool object, it might get confused when called from differen threads?

**Comment by laeubi** [comment]
But maybe there is more an intrinsic problem as I getting sometime spurious error also on [other places](https://github.com/jboss-javassist/javassist/issues/362).
