### ISSUE TITLE
Inconsistent stack height

### ISSUE THREAD

**Issue by kuznet1** [jboss-javassist/javassist#376]
This simple snippet
```
public class Main {
    public static void main(String[] args) {
        CtClass badClass = ClassPool.getDefault().makeClass("badClass");
        String src = String.join("\n",
                "public void eval() {",
                "    long t=0;",
                "    if (true) {",
                "        t++;\n".repeat(8192),
                "    }",
                "}");
        System.out.println(src);
        try {
            badClass.addMethod(CtMethod.make(src, badClass)); // <-- falls here
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
causes
```
javassist.CannotCompileException: [source error] eval ()V in badClass: inconsistent stack height Index -32761 out of bounds for length 32776
	at javassist.CtNewMethod.make(CtNewMethod.java:84)
	at javassist.CtNewMethod.make(CtNewMethod.java:50)
	at javassist.CtMethod.make(CtMethod.java:140)
	at com.company.Main.main(Main.java:19)
Caused by: compile error: eval ()V in badClass: inconsistent stack height Index -32761 out of bounds for length 32776
	at javassist.compiler.Javac.compile(Javac.java:110)
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	... 3 more
```
The exact same class compiles successfully by javac.
I did some research and found out that javassist [used](https://github.com/jboss-javassist/javassist/blob/master/src/main/javassist/compiler/CodeGen.java#L434) for `if` [GOTO](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-6.html#jvms-6.5.goto) only, which allows jump up to 32767 bytes offset, but javac can use [GOTO_W](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-6.html#jvms-6.5.goto_w) for large blocks. I think it's not a good idea to use GOTO_W always because it can significantly blow up a bytecode and classes that compiled successfully may reach limit of method length for 65536 bytes. So, can we just "shift" `if` body for two bytes [here](https://github.com/jboss-javassist/javassist/blob/master/src/main/javassist/compiler/CodeGen.java#L439) if we understand that we have to use GOTO_W?

**Comment by StarrLucky** [comment]
Any hopes that this will be fixed?
