### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by clankill3r** [jboss-javassist/javassist#396]
The following line gives a problem:
```java
"       java.lang.reflect.Method m = cls.getDeclaredMethod(\"valueOf\", boolean.class);",
```

> javassist.CannotCompileException: [source error] getDeclaredMethod(java.lang.String) not found in java.lang.Class

Here the full error:

> javassist.CannotCompileException: [source error] getDeclaredMethod(java.lang.String) not found in java.lang.Class
>         at javassist.CtBehavior.insertBefore(CtBehavior.java:806)
>         at javassist.CtBehavior.insertBefore(CtBehavior.java:766)
>         at metron.Javassist_Bug.premain(Javassist_Bug.java:45)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
>         at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
> Caused by: compile error: getDeclaredMethod(java.lang.String) not found in java.lang.Class
>         at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:777)
>         at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:723)
>         at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
>         at javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
>         at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
>         at javassist.compiler.CodeGen.atDeclarator(CodeGen.java:819)
>         at javassist.compiler.ast.Declarator.accept(Declarator.java:103)
>         at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
>         at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
>         at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
>         at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
>         at javassist.compiler.MemberCodeGen.atTryStmnt(MemberCodeGen.java:234)
>         at javassist.compiler.CodeGen.atStmnt(CodeGen.java:397)
>         at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
>         at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
>         at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
>         at javassist.compiler.Javac.compileStmnt(Javac.java:578)
>         at javassist.CtBehavior.insertBefore(CtBehavior.java:786)
>         ... 8 more

Here the code:

```java
package metron;

import java.lang.instrument.Instrumentation;
import javassist.*;


public class Javassist_Bug {


    public static void main(String[] args) {
       // this works:
        try {
            Class<?> cls = Class.forName("java.lang.String");
            System.out.println(cls.getName());
            java.lang.reflect.Method m = cls.getDeclaredMethod("valueOf", boolean.class);
        }
        catch (Exception e) {
            // swallow exception
        }
    }


    public static void premain(String agentArgs, Instrumentation inst) {

        try {
            ClassPool pool = ClassPool.getDefault();
            CtClass cc = pool.get("java.lang.Thread");

            CtMethod m_start = cc.getDeclaredMethod("start");
            
            m_start.insertBefore(String.join("\n",
                "{",
                "   try {",
                "       Class cls = Class.forName(\"java.lang.String\");", // Class<?> does not work!
                "       System.out.println(cls.getName());",
                "       java.lang.reflect.Method m = cls.getDeclaredMethod(\"valueOf\", boolean.class);",
                "   }",
                "   catch (Exception e) {",
                "       // swallow exception",
                "   }",
                "}"
            ));

            cc.writeFile("./bin");

            System.out.println("\n\nwrote new Thread class!\n\n");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
```

I also tried it on something other then using the Thread or String class but just on a class I created but the error stays.
I hope someone can help.

**Comment by clankill3r** [comment]
Ok also invoking did not work: `"       m.invoke(null);",`.

I noticed that for things where the javassist compiler fails I can just wrap what I want in a method.
For example for this line:

```java
"       java.lang.reflect.Method m = cls.getDeclaredMethod(\"apples\");",
```

I can use:

```java
"       java.lang.reflect.Method m = metron.Javassist_Bug.get_method_workaround(cls, \"apples\");",
```

Where `get_method_workaround` looks like:

```java
    static public Method get_method_workaround(Class<?> cls, String name) {
        try {
            return cls.getDeclaredMethod(name);
        } catch (NoSuchMethodException | SecurityException e) {
            e.printStackTrace();
        }
        return null;
    }
```

I think some interesting places to look at are:

class: MemberResolver  
method: lookupMethod  

class: TypeChecker  
method: atMethodCallCore  

I had some thought of what it could be, but I think now those thoughts could be wrong so I leave them for myself.

**Comment by xixiU** [comment]
Do you solve the same problem?

**Comment by clankill3r** [comment]
nope, I use the workaround.
