### ISSUE TITLE
cannot run in jdk17

### ISSUE THREAD

**Issue by funky-eyes** [jboss-javassist/javassist#400]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3aefe5e5
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at javassist.util.proxy.SecurityActions$3.run(SecurityActions.java:94)
	at javassist.util.proxy.SecurityActions$3.run(SecurityActions.java:90)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at javassist.util.proxy.SecurityActions.getMethodHandle(SecurityActions.java:89)
	at javassist.util.proxy.DefineClassHelper$SecuredPrivileged$2.getDefineClassMethodHandle(DefineClassHelper.java:143)
	at javassist.util.proxy.DefineClassHelper$SecuredPrivileged$2.<init>(DefineClassHelper.java:136)
	at javassist.util.proxy.DefineClassHelper$SecuredPrivileged.<clinit>(DefineClassHelper.java:134)
	... 38 more

Has been used 3.28.0-GA version

**Comment by zmiklank** [comment]
Hi, is there any plan for supporting jdk17 in upstream in the (near) future?

**Comment by chibash** [comment]
This problem is caused by the same reason as mentioned here,
http://www.javassist.org/html/javassist/CtClass.html#toClass()

We must find a similar work-around to bypass the strict access control by jdk 17.

**Comment by chibash** [comment]
Giving this option to the JVM `--add-opens java.base/java.lang=ALL-UNNAMED` is a quick workaround.

**Comment by chibash** [comment]
@takezaki , I have just released 3.29.0-GA.

**Comment by a364176773** [comment]
> Giving this option to the JVM `--add-opens java.base/java.lang=ALL-UNNAMED` is a quick workaround.

This seems like a temporary solution and hopefully JDK 17 will be formally supported in the future, thx
