### ISSUE TITLE
javassist.CannotCompileException: [source error] no such class: java.lang.System.out

### ISSUE THREAD

**Issue by StayWithMeSenpai** [jboss-javassist/javassist#416]
Method modification:

```java
CtMethod m = renderEffect.getCtMethod(classPool, compiledClass);
System.out.println("Hooked Method: " + m.getName());
m.insertBefore("java.lang.System.out.println(\"wow, its rendering\");");
```

Classpool:

```java
ClassPool classPool = ClassPool.getDefault();
classPool.appendClassPath(jar.toString());
classPool.appendClassPath(new File(InjectedAgent.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getPath().toString());
```

Error:

> [STDERR]: javassist.CannotCompileException: [source error] no such class: java.lang.System.out
> [STDERR]:	at javassist.CtBehavior.insertBefore(CtBehavior.java:806)
> [STDERR]: 	at javassist.CtBehavior.insertBefore(CtBehavior.java:766)

**Comment by dwOrigin** [comment]
`Exception in thread "main" javassist.CannotCompileException: [source error] no such class: RandomAccessFile`  I get a similar problem and how should i do to solve this one
