### ISSUE TITLE
Compile error: ) is missing

### ISSUE THREAD

**Issue by TheSirCororo** [jboss-javassist/javassist#425]
I can compile this code by real javac compiler, but can't compile it with javaassist compiler:
https://pastebin.com/YhPzWGwz
javassist code:
```CtField.make("private static final String key = ${obfuscate(key)};", ctClass);```
Error:
```
Exception in thread "main" javassist.CannotCompileException: [source error] ) is missing
	at javassist.CtField.make(CtField.java:166)
	at ru.cororo.Licenser.replaceBytecode(MoonLicenser.kt:56)
	at ru.cororo.Licenser.main(MoonLicenser.kt:19)
Caused by: compile error: ) is missing
	at javassist.compiler.Parser.parsePrimaryExpr(Parser.java:1247)
	at javassist.compiler.Parser.parsePostfix(Parser.java:1029)
	at javassist.compiler.Parser.parseCast(Parser.java:920)
	at javassist.compiler.Parser.parseUnaryExpr(Parser.java:885)
	at javassist.compiler.Parser.parseBinaryExpr(Parser.java:774)
	at javassist.compiler.Parser.parseConditionalExpr(Parser.java:718)
	at javassist.compiler.Parser.parseExpression(Parser.java:698)
	at javassist.compiler.Parser.parseField(Parser.java:80)
	at javassist.compiler.Parser.parseMember1(Parser.java:66)
	at javassist.compiler.Javac.compile(Javac.java:89)
	at javassist.CtField.make(CtField.java:161)
	... 2 more
```

**Comment by TheSirCororo** [comment]
Fixed by updating
