### ISSUE TITLE
lamda expressions - compile exception

### ISSUE THREAD

**Issue by bojanv55** [jboss-javassist/javassist#44]
When trying to use lambda in setBody string, i get this (the problem is this line:

$CONSTRUCTORS.put("key", new Function<Integer, Probna>() {
            public Probna apply(Integer ordinal) {
               //more code that returns new Probna(ordinal);
            }
        });

Same problem happens if i use (ordinal) -> new Probna(ordinal);

Exception in thread "main" javassist.CannotCompileException: [source error] syntax error near "Function<Integer, Pr"
	at javassist.CtBehavior.setBody(CtBehavior.java:446)
	at javassist.CtBehavior.setBody(CtBehavior.java:412)
	at DynamicEnumOld.makeDynamic(DynamicEnumOld.java:104)
	at DynamicEnumOld.main(DynamicEnumOld.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: compile error: syntax error near "Function<Integer, Pr"
	at javassist.compiler.Parser.parseNew(Parser.java:1293)
	at javassist.compiler.Parser.parsePrimaryExpr(Parser.java:1244)
	at javassist.compiler.Parser.parsePostfix(Parser.java:1031)
	at javassist.compiler.Parser.parseUnaryExpr(Parser.java:888)
	at javassist.compiler.Parser.parseBinaryExpr(Parser.java:775)
	at javassist.compiler.Parser.parseConditionalExpr(Parser.java:719)
	at javassist.compiler.Parser.parseExpression(Parser.java:699)
	at javassist.compiler.Parser.parseArgumentList(Parser.java:1332)
	at javassist.compiler.Parser.parseMethodCall(Parser.java:1180)
	at javassist.compiler.Parser.parsePostfix(Parser.java:1036)
	at javassist.compiler.Parser.parseUnaryExpr(Parser.java:888)
	at javassist.compiler.Parser.parseBinaryExpr(Parser.java:775)
	at javassist.compiler.Parser.parseConditionalExpr(Parser.java:719)
	at javassist.compiler.Parser.parseExpression(Parser.java:699)
	at javassist.compiler.Parser.parseDeclarationOrExpression(Parser.java:591)
	at javassist.compiler.Parser.parseStatement(Parser.java:277)
	at javassist.compiler.Parser.parseBlock(Parser.java:289)
	at javassist.compiler.Parser.parseStatement(Parser.java:243)
	at javassist.compiler.Javac.compileBody(Javac.java:214)
	at javassist.CtBehavior.setBody(CtBehavior.java:438)
	... 8 more

**Comment by chibash** [comment]
Ah, Java 8 syntax, including a lambda, is not supported by the source-to-bytecode compiler although Javassist can handle it.

**Comment by heweimxcz** [comment]
like this
String method = "CtMethod.make("public   static  int RobustPublicaddActionInterceptor\$lambda-1(com.nio.lego.lgrouter.router.action.interceptor.ActionInterceptor var0,com.nio.lego.lgrouter.router.action.interceptor.ActionInterceptor var1){return addActionInterceptor\$lambda-1(var0,var1);}", ctClass)"
CtMethod.make( method, ctClasss)

**Comment by heweimxcz** [comment]
like this
String method = "public   static  int RobustPublicaddActionInterceptor\$lambda-1(com.xxx.xxx.xxx.router.action.interceptor.ActionInterceptor var0,com.xxx.xxx.xxx.router.action.interceptor.ActionInterceptor var1){return addActionInterceptor\$lambda-1(var0,var1);}"
CtMethod.make(method, ctClass)

**Comment by heweimxcz** [comment]
it happens error

**Comment by heweimxcz** [comment]
[source error] syntax error near r$lambda-1

**Comment by chibash** [comment]
It seems that `$lambda-1` is not a valid Java name; maybe it's only available in bytecode.

**Comment by chibash** [comment]
I don't know.  How did you get that `.. $lambda-1$ method?  Do you have the original source code of that?

**Comment by heweimxcz** [comment]
![image](https://user-images.githubusercontent.com/9306631/221580685-33921d15-0ee6-4053-b655-658fddfd3430.png)

**Comment by heweimxcz** [comment]
this class file has that synthetic method

**Comment by chibash** [comment]
Is this Kotlin?  Then I'm afraid that I cannot help you...

**Comment by heweimxcz** [comment]
> Is this Kotlin? Then I'm afraid that I cannot help you...

yes , it is kotlin, thank for your reply
