### ISSUE TITLE
java.lang.ClassFormatError: Truncated class file

### ISSUE THREAD

**Issue by micartey** [jboss-javassist/javassist#455]
I am unzipping my jar file and changing a class (adding a static method) and writing the output to that file.
Occasionally (depending on the jar file I am modifying) I get the error specified above:

```
java.lang.ClassFormatError: Truncated class file
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_362]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_362]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_362]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_362]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_362]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_362]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_362]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_362]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_362]
	...
```

1. Why is this happening?
2. What do I need to do, to solve this?

**Comment by micartey** [comment]
Using ASM instead solves the issue.
However, I dislike using ASM compared to Javassist...
