### ISSUE TITLE
Wrong method locals after method replacing

### ISSUE THREAD

**Issue by vliux** [jboss-javassist/javassist#62]
I'm trying to use Javassit in Android build with Maven. The orignial method is like this:
```
public class MyActivity extends Activity{
    public void onCreate(Bundle bundle){
        Log.d("...");
        super.onCreate(bundle);
        setUI();
    }

    public void setUI(){
        // businsess logic here ...
    }
}
```

I'd like to replace the invoke of setUI() to another static method:
```
public class InstrumentUtil{
    pubilc static void setUI(MyActivity m){
        // instrument logic at first ...
        m.setUI(); 
    }
}
```

The instrumentation code is like below:
```
CtMethod method = activityCtClz.getDeclaredMethod("onCreate", new CtClass[]{bundleCtClz});
method.instrument(new ExprEditor() {
            @Override
            public void edit(MethodCall m) throws CannotCompileException {
                if (m.getMethodName().equals("setUI")) {
                    m.replace("$_=com.example.testapp.InstrumentUtil.setUI($0);");
                }
            }
        });
```

However, the generated class bytecode is wrong at locals as below. The line below "Code" shows "locals=4" but the actual parameter number is 2, which causes "stack underflow" exception at dex phase in building time.
```
public void onCreate(android.os.Bundle);
    flags: ACC_PUBLIC
    Code:
      stack=2, **locals=4**, args_size=2
         0: ldc           #2                  // String vliux
         2: ldc           #3                  // String in MyActivity.onCreate()
         4: invokestatic  #4                  // Method android/util/Log.d:(Ljava/lang/String;Ljava/lang/String;)I
         7: pop           
         8: aload_0       
         9: aload_1       
        10: invokespecial #5                  // Method android/app/Activity.onCreate:(Landroid/os/Bundle;)V
        13: aload_0       
        14: astore_2      
        15: aload_2       
        16: invokestatic  #50                 // Method com/example/testapp/InstrumentUtil.setUI:(Lcom/example/testapp/MyActivity;)V
        19: astore_3      
        20: return        
      LineNumberTable:
        line 13: 0
        line 14: 8
        line 15: 13
        line 16: 20
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
               0      21     0  this   Lcom/example/testapp/MyActivity;
               0      21     1 savedInstanceState   Landroid/os/Bundle;
```

More information:
The build step is that:
1. the classes are compiled
2. instrument class files with Javassist
3. dex the generated class files with Android build tool
Actually the "stack underflow" error was even reported during dexing. The stack trace is like blow, which might be helpful:
```
[INFO] Create dex file:/home/vliux/Code/alibaba/hurdle_jassist/testapp/target/classes to:/home/vliux/Code/alibaba/hurdle_jassist/testapp/target/classes.dex
Exception in thread "pool-16-thread-2" com.android.dx.cf.code.SimException: stack: underflow
	at com.android.dx.cf.code.ExecutionStack.throwSimException(ExecutionStack.java:341)
	at com.android.dx.cf.code.ExecutionStack.peek(ExecutionStack.java:206)
	at com.android.dx.cf.code.ExecutionStack.pop(ExecutionStack.java:253)
	at com.android.dx.cf.code.BaseMachine.popArgs(BaseMachine.java:130)
	at com.android.dx.cf.code.BaseMachine.popArgs(BaseMachine.java:157)
	at com.android.dx.cf.code.Simulator$SimVisitor.visitLocal(Simulator.java:591)
	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:524)
	at com.android.dx.cf.code.Simulator.simulate(Simulator.java:94)
	at com.android.dx.cf.code.Ropper.processBlock(Ropper.java:698)
	at com.android.dx.cf.code.Ropper.doit(Ropper.java:653)
	at com.android.dx.cf.code.Ropper.convert(Ropper.java:266)
	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:284)
	at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:141)
	at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:95)
	at com.android.dx.command.dexer.Main.processClass(Main.java:708)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:660)
	at com.android.dx.command.dexer.Main.access$600(Main.java:81)
	at com.android.dx.command.dexer.Main$ParallelProcessor.run(Main.java:1576)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
...at bytecode offset 00000013
locals[0000]: Lcom/example/testapp/MyActivity;
locals[0001]: Landroid/os/Bundle;
locals[0002]: Lcom/example/testapp/MyActivity;
locals[0003]: <invalid>
...while working on block 0013
...while working on method onCreate:(Landroid/os/Bundle;)V
...while processing onCreate (Landroid/os/Bundle;)V
...while processing com/example/testapp/MyActivity.class
```
You see that there are 4 local variables after method replacing.
Did I make anything wrong in instrumentation?

**Comment by chibash** [comment]
"locals=4" is correct because the number includes local variables used in the method body.
See line 14 and 19, where local variables #2 and #3 are used.

**Comment by vliux** [comment]
chibash, Thanks for replying! But I'm still confused about the error in dexing.
Seems the last(4th) parameter is invalid? As you can see from stack trace:
```
locals[0000]: Lcom/example/testapp/MyActivity;
locals[0001]: Landroid/os/Bundle;
locals[0002]: Lcom/example/testapp/MyActivity;
locals[0003]: <invalid>
```
InstrumentUtil.setUI() is a static method taking only one parameter, so locals[002] is correct, but I can't see what does locals[003] work for. Also from the bytecode of line 19, there is a 'astore_3' but no 'aload_3'.

**Comment by chibash** [comment]
Sorry this reply is too late...

I think this line is wrong:

    m.replace("$_=com.example.testapp.InstrumentUtil.setUI($0);");

because setUi() returns void.  So

    m.replace("com.example.testapp.InstrumentUtil.setUI($0);");

should be a correct call.
