### ISSUE TITLE
Verify exception with byte code for calling default methods

### ISSUE THREAD

**Issue by ml-bauer** [jboss-javassist/javassist#74]
The following code throws a verify exception (java version is 1.8.0_77)

```
package test;

import javassist.CannotCompileException;
import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtNewMethod;
import javassist.NotFoundException;

public class JavassistTest {
    public static interface A {
        default int aMethod() {
            return 42;
        }
    }
    
    public static void main(String[] args) throws NotFoundException, CannotCompileException, InstantiationException, IllegalAccessException {
        ClassPool pool = ClassPool.getDefault();
        
        CtClass ctClass = pool.makeClass("test.Test");
        ctClass.addInterface(pool.get(A.class.getName()));
        
        ctClass.addMethod(CtNewMethod.make("public int aMethod() { return 1 + " + A.class.getName() + ".super.aMethod(); }", ctClass));
        
        Class klass = ctClass.toClass();
        klass.newInstance();
    }
}
```

The reported exception is:

```
Exception in thread "main" java.lang.VerifyError: Illegal type at constant pool entry 12 in class test.Test
Exception Details:
  Location:
    test/Test.aMethod()I @2: invokespecial
  Reason:
    Constant pool index 12 is invalid
  Bytecode:
    0x0000000: 042a b700 0c60 ac                      

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
	at java.lang.Class.getConstructor0(Class.java:3067)
	at java.lang.Class.newInstance(Class.java:408)
	at test.JavassistTest.main(JavassistTest.java:31)

```

**Comment by ml-bauer** [comment]
javassist version is 3.20.0-GA

**Comment by chibash** [comment]
This test code does not throw an exception with the current HEAD of javassist.
An upcoming release will fix this bug.
