### ISSUE TITLE
java.lang.VerifyError: Inconsistent stackmap frames at branch target

### ISSUE THREAD

**Issue by hatcherunh** [jboss-javassist/javassist#78]
Getting VerifyError when trying to execute a static method in a generated class.

Using 3.20.0 with Java 1.8.0_51.

The generated code will compile and run with javac/java.

Here's the code:

```
import javassist.CannotCompileException;
import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtConstructor;
import javassist.CtMethod;
import javassist.CtNewConstructor;
import javassist.CtNewMethod;
import javassist.Loader;
import javassist.NotFoundException;
import javassist.Modifier;

public class jA
{
  public static void fatal(String message)
  {
    System.err.println(message);
    System.exit(-1);
  }

  public static void main(String[] args)
  {
    ClassPool pool = ClassPool.getDefault();
    pool.importPackage("ts.Message");
    pool.importPackage("ts.support");

    CtClass theClass = pool.makeClass("test1");

    String theSignature = "public static void main(String args[])" + "{}";
    CtMethod theMethod = null;
    try {
      theMethod = CtNewMethod.make(theSignature, theClass);
    } catch (CannotCompileException ex) {
      fatal("cannot compile the generated main method signature: " +
        ex.getReason());
    }

  String theMethodBody = "";
  theMethodBody += "  {\n";
  theMethodBody += "    double var_tempCounter_0 = 0;\n";
  theMethodBody += "    boolean temp23 = true;\n";
  theMethodBody += "    boolean temp10 = true;\n";
  theMethodBody += "    while(temp10)\n";
  theMethodBody += "    {\n";
  theMethodBody += "      double temp11 = var_tempCounter_0;\n";
  theMethodBody += "      if(temp11 < 1.0)\n";
  theMethodBody += "        break;\n";
  theMethodBody += "    }\n";
  theMethodBody += "    while(temp23)\n";
  theMethodBody += "    {\n";
  theMethodBody += "        temp23 = false;\n";
  theMethodBody += "        double temp20 = var_tempCounter_0;\n";
  theMethodBody += "        boolean temp22 = temp20 < 1.0;\n";
  theMethodBody += "    }\n";
  theMethodBody += "  }\n";
    try {
      theMethod.setBody(theMethodBody);
    } catch (CannotCompileException ex) {
      fatal("cannot compile the generated main method body: " +
        ex.getReason());
    }

    try {
      theClass.addMethod(theMethod);
    } catch (CannotCompileException ex) {
      fatal("cannot add the main method into the main class: " +
        ex.getReason());
    }

    try {
      theClass.addConstructor(CtNewConstructor.defaultConstructor(theClass));
    } catch (CannotCompileException ex) {
      fatal("cannot add a default constructor to the main class: " +
        ex.getReason());
    }

    Loader classLoader = new Loader(pool);
    try {
      classLoader.run("test1", new String[0]);
    } catch (Throwable ex) {
      ex.printStackTrace();
      fatal("uncaught Java exception in execution of generated code:");
    }
  }
}
```

Here is the output:

```
java.lang.VerifyError: Inconsistent stackmap frames at branch target 48
Exception Details:
  Location:
    test1.main([Ljava/lang/String;)V @48: iconst_1
  Reason:
    Type top (current frame, locals[6]) is not assignable to double (stack map, locals[6])
  Current Frame:
    bci: @41
    flags: { }
    locals: { '[Ljava/lang/String;', double, double_2nd, integer, integer, top, top, double, double_2nd }
    stack: { integer }
  Stackmap Frame:
    bci: @48
    flags: { }
    locals: { '[Ljava/lang/String;', double, double_2nd, integer, integer, top, double, double_2nd }
    stack: { }
  Bytecode:
    0x0000000: 0387 4804 3e04 3604 a700 1027 3905 1805
    0x0000010: 0f98 9c00 06a7 0008 1504 9aff f1a7 0016
    0x0000020: 033e 2739 0718 070f 989b 0007 03a7 0004
    0x0000030: 0436 091d 9aff ecb1                    
  Stackmap Table:
    append_frame(@11,Double,Integer,Integer)
    same_frame(@24)
    same_frame(@29)
    same_frame(@32)
    append_frame(@48,Top,Double)
    same_locals_1_stack_item_frame(@49,Integer)
    chop_frame(@51,1)

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at javassist.Loader.run(Loader.java:288)
	at jA.main(jA.java:92)
uncaught Java exception in execution of generated code:
```
`

**Comment by kuznet1** [comment]
https://issues.jboss.org/browse/JASSIST-262 fixed similar problem. Maybe this is fixed

**Comment by chibash** [comment]
The code above doesn't produce an error any longer.
So I suppose this bug has been already fixed.
