### ISSUE TITLE
some issue in anonymous inner class

### ISSUE THREAD

**Issue by ascrutae** [jboss-javassist/javassist#94]
I use javassist to enhance my code. Here is my sample code
```java
ClassPool classPool = ClassPool.getDefault();
CtClass ctClass = classPool.get(App.class.getName());
CtConstructor constructor = ctClass.getDeclaredConstructor(null);
constructor.insertAfter("new " + FieldSetter.class.getName() + "(){ public void set(Object object){ System.out.println(\"Hello World\");};");
```
but an exception was throw. Here are the log. what should I do to support anonymous inner class?
```
Exception in thread "main" javassist.CannotCompileException: [source error] ; is missing
	at javassist.CtBehavior.insertAfter(CtBehavior.java:877)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:792)
	at com.ai.test.App.main(App.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: compile error: ; is missing
	at javassist.compiler.Parser.parseDeclarationOrExpression(Parser.java:594)
	at javassist.compiler.Parser.parseStatement(Parser.java:277)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:892)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:851)
	... 7 more
```

**Comment by chibash** [comment]
That syntax is not supported because it internally creates a new class.
